slack:
  app_id:
  client_id:
  client_secret:
  signing_secret:
  verification_token:
  bot_oauth_token:
  team_id:
sendgrid:
  api_key:
openai:
  baseurl:
  api_key:
  model:
  temperature:
  max_tokens:
  top_p:
  frequency_penalty:
  presence_penalty:
  stop:
